-- MySQL Script generated by MySQL Workbench
-- jeu 17 aoû 2017 11:01:20 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poker` DEFAULT CHARACTER SET utf8 ;
USE `poker` ;

-- -----------------------------------------------------
-- Table `poker`.`parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`parties` (
  `id` INT NOT NULL,
  `nombre de parties jouées` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`championat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`championat` (
  `id` INT NOT NULL,
  `nombre de championats joués` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poker`.`joueurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `poker`.`joueurs` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `sexe` VARCHAR(1) NOT NULL,
  `adresse` VARCHAR(255) NULL,
  `parties_id` INT NOT NULL,
  `championat_id` INT NOT NULL,
  PRIMARY KEY (`id`, `championat_id`),
  INDEX `fk_joueurs_parties_idx` (`parties_id` ASC),
  INDEX `fk_joueurs_championat1_idx` (`championat_id` ASC),
  CONSTRAINT `fk_joueurs_parties`
    FOREIGN KEY (`parties_id`)
    REFERENCES `poker`.`parties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joueurs_championat1`
    FOREIGN KEY (`championat_id`)
    REFERENCES `poker`.`championat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
