-- MySQL Script generated by MySQL Workbench
-- mer 16 aoû 2017 16:09:58 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema timbre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema timbre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timbre` DEFAULT CHARACTER SET utf8 ;
USE `timbre` ;

-- -----------------------------------------------------
-- Table `timbre`.`timbres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timbre`.`timbres` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `timbre`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timbre`.`collection` (
  `id` INT NOT NULL,
  `pays` VARCHAR(45) NULL,
  `taille_mm` INT(15) NULL,
  `timbres_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_collection_timbres_idx` (`timbres_id` ASC),
  CONSTRAINT `fk_collection_timbres`
    FOREIGN KEY (`timbres_id`)
    REFERENCES `timbre`.`timbres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
