-- MySQL Script generated by MySQL Workbench
-- jeu 17 aoû 2017 09:47:57 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema horaire
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horaire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horaire` DEFAULT CHARACTER SET utf8 ;
USE `horaire` ;

-- -----------------------------------------------------
-- Table `horaire`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horaire`.`classes` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horaire`.`enfants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horaire`.`enfants` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(255) NULL,
  `classes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enfants_classes1_idx` (`classes_id` ASC),
  CONSTRAINT `fk_enfants_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `horaire`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horaire`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horaire`.`cours` (
  `id` INT NOT NULL,
  `intitulé` VARCHAR(255) NOT NULL,
  `code_cours` VARCHAR(255) NOT NULL,
  `prof` VARCHAR(255) NOT NULL,
  `horaire` TIME(4) NOT NULL,
  `enfants_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cours_enfants_idx` (`enfants_id` ASC),
  CONSTRAINT `fk_cours_enfants`
    FOREIGN KEY (`enfants_id`)
    REFERENCES `horaire`.`enfants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horaire`.`cours_has_classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horaire`.`cours_has_classes` (
  `cours_id` INT NOT NULL,
  `classes_id` INT NOT NULL,
  PRIMARY KEY (`cours_id`, `classes_id`),
  INDEX `fk_cours_has_classes_classes1_idx` (`classes_id` ASC),
  INDEX `fk_cours_has_classes_cours1_idx` (`cours_id` ASC),
  CONSTRAINT `fk_cours_has_classes_cours1`
    FOREIGN KEY (`cours_id`)
    REFERENCES `horaire`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cours_has_classes_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `horaire`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horaire`.`classes_has_cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horaire`.`classes_has_cours` (
  `classes_id` INT NOT NULL,
  `cours_id` INT NOT NULL,
  PRIMARY KEY (`classes_id`, `cours_id`),
  INDEX `fk_classes_has_cours_cours1_idx` (`cours_id` ASC),
  INDEX `fk_classes_has_cours_classes1_idx` (`classes_id` ASC),
  CONSTRAINT `fk_classes_has_cours_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `horaire`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_cours_cours1`
    FOREIGN KEY (`cours_id`)
    REFERENCES `horaire`.`cours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
