-- MySQL Script generated by MySQL Workbench
-- mer 16 aoû 2017 16:53:53 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cuisine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cuisine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cuisine` DEFAULT CHARACTER SET utf8 ;
USE `cuisine` ;

-- -----------------------------------------------------
-- Table `cuisine`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuisine`.`recette` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `quantité` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuisine`.`ingrédient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuisine`.`ingrédient` (
  `id` INT NOT NULL,
  `ingrédient_name` VARCHAR(255) NOT NULL,
  `quantité` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cuisine`.`recette_has_ingrédient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cuisine`.`recette_has_ingrédient` (
  `recette_id` INT NOT NULL,
  `ingrédient_id` INT NOT NULL,
  PRIMARY KEY (`recette_id`, `ingrédient_id`),
  INDEX `fk_recette_has_ingrédient_ingrédient1_idx` (`ingrédient_id` ASC),
  INDEX `fk_recette_has_ingrédient_recette_idx` (`recette_id` ASC),
  CONSTRAINT `fk_recette_has_ingrédient_recette`
    FOREIGN KEY (`recette_id`)
    REFERENCES `cuisine`.`recette` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_has_ingrédient_ingrédient1`
    FOREIGN KEY (`ingrédient_id`)
    REFERENCES `cuisine`.`ingrédient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
