-- MySQL Script generated by MySQL Workbench
-- mer 16 aoû 2017 15:08:50 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classe` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `academic_year` YEAR NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`children`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`children` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_children_classe1_idx` (`classe_id` ASC),
  CONSTRAINT `fk_children_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `mydb`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brol` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `children_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_brol_children_idx` (`children_id` ASC),
  CONSTRAINT `fk_brol_children`
    FOREIGN KEY (`children_id`)
    REFERENCES `mydb`.`children` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classe_has_profs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classe_has_profs` (
  `classe_id` INT NOT NULL,
  `profs_id` INT NOT NULL,
  PRIMARY KEY (`classe_id`, `profs_id`),
  INDEX `fk_classe_has_profs_profs1_idx` (`profs_id` ASC),
  INDEX `fk_classe_has_profs_classe1_idx` (`classe_id` ASC),
  CONSTRAINT `fk_classe_has_profs_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `mydb`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classe_has_profs_profs1`
    FOREIGN KEY (`profs_id`)
    REFERENCES `mydb`.`profs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
